version: '3'
services:
  krenamer:
    build: .
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TAKE_CONFIG_OWNERSHIP=1
      - CLEAN_TMP_DIR=1
      - SECURE_CONNECTION=1
      - VNC_PASSWORD=password
    volumes:
      - '${VOLUME_CONFIG}:/home/krenamer/config/'
    ports:
      - '5800:5800'
      - '5900:5900'
